In [1]:
from tqdm.notebook import tqdm
%matplotlib inline 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import datetime
import matplotlib.font_manager as fm

font_name = fm.FontProperties(fname=r"C:\Windows\Fonts\malgun.ttf").get_name()
plt.rc("font", family=font_name)

import matplotlib as mlp
mlp.rcParams["axes.unicode_minus"] = False

from urllib.request import urlopen
from bs4 import BeautifulSoup
import requests
import time
import random
from tqdm import tqdm_notebook

import folium
from IPython.display import display

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import os
import traceback

from sklearn.linear_model import LinearRegression

In [2]:
tot_items = pd.read_excel("C:\\juna27\\Git\\data\\data1\\품목별_소비자물가지수_품목성질별_2020100__20230425170328(품목별_기본_시도별).xlsx")

C:\Users\acorn\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [3]:
tot_items

,시도별,시점,농축수산물,공업제품,전기 · 가스 · 수도,집세,공공서비스,개인서비스
0,서울특별시,2012,84.572,94.385,116.948,85.828,96.900,85.290
1,서울특별시,2013,83.128,95.505,122.581,88.279,97.600,86.444
2,서울특별시,2014,80.868,97.119,127.783,90.754,98.230,87.971
3,서울특별시,2015,83.425,97.842,116.394,93.574,99.893,89.690
4,서울특별시,2016,86.541,97.718,103.955,95.904,101.421,92.102
...,...,...,...,...,...,...,...,...
171,제주특별자치도,2018,94.969,101.055,99.231,100.625,100.639,97.601
172,제주특별자치도,2019,94.868,100.738,99.392,100.387,100.001,99.235
173,제주특별자치도,2020,100.000,100.000,100.000,100.000,100.000,100.000
174,제주특별자치도,2021,108.940,103.160,99.360,100.010,100.710,101.950
175,제주특별자치도,2022,114.180,111.430,109.410,101.010,101.810,108.670

In [4]:
# birth_rate = [1.30, 1.19, 1.21, 1.24, 1.17, 1.05, 0.98, 0.92, 0.84, 0.81, 0.78]

In [5]:
# tot_items["출산율"] = birth_rate

In [6]:
tot_items

,시도별,시점,농축수산물,공업제품,전기 · 가스 · 수도,집세,공공서비스,개인서비스
0,서울특별시,2012,84.572,94.385,116.948,85.828,96.900,85.290
1,서울특별시,2013,83.128,95.505,122.581,88.279,97.600,86.444
2,서울특별시,2014,80.868,97.119,127.783,90.754,98.230,87.971
3,서울특별시,2015,83.425,97.842,116.394,93.574,99.893,89.690
4,서울특별시,2016,86.541,97.718,103.955,95.904,101.421,92.102
...,...,...,...,...,...,...,...,...
171,제주특별자치도,2018,94.969,101.055,99.231,100.625,100.639,97.601
172,제주특별자치도,2019,94.868,100.738,99.392,100.387,100.001,99.235
173,제주특별자치도,2020,100.000,100.000,100.000,100.000,100.000,100.000
174,제주특별자치도,2021,108.940,103.160,99.360,100.010,100.710,101.950
175,제주특별자치도,2022,114.180,111.430,109.410,101.010,101.810,108.670

In [7]:
tot_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176 entries, 0 to 175
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   시도별           176 non-null    object
 1   시점            176 non-null    int64
 2   농축수산물         176 non-null    float64
 3   공업제품          176 non-null    float64
 4   전기 · 가스 · 수도  176 non-null    float64
 5   집세            176 non-null    float64
 6   공공서비스         176 non-null    float64
 7   개인서비스         176 non-null    float64
dtypes: float64(6), int64(1), object(1)
memory usage: 11.1+ KB

In [8]:
tot_items.set_index("시점", inplace=True)

In [9]:
tot_items

             시도별    농축수산물     공업제품  전기 · 가스 · 수도       집세    공공서비스    개인서비스
시점
2012    　　　서울특별시   84.572   94.385       116.948   85.828   96.900   85.290
2013    　　　서울특별시   83.128   95.505       122.581   88.279   97.600   86.444
2014    　　　서울특별시   80.868   97.119       127.783   90.754   98.230   87.971
2015    　　　서울특별시   83.425   97.842       116.394   93.574   99.893   89.690
2016    　　　서울특별시   86.541   97.718       103.955   95.904  101.421   92.102
...          ...      ...      ...           ...      ...      ...      ...
2018  　　　제주특별자치도   94.969  101.055        99.231  100.625  100.639   97.601
2019  　　　제주특별자치도   94.868  100.738        99.392  100.387  100.001   99.235
2020  　　　제주특별자치도  100.000  100.000       100.000  100.000  100.000  100.000
2021  　　　제주특별자치도  108.940  103.160        99.360  100.010  100.710  101.950
2022  　　　제주특별자치도  114.180  111.430       109.410  101.010  101.810  108.670

[176 rows x 7 columns]

In [10]:
birth_rate = [1.30, 1.19, 1.21, 1.24, 1.17, 1.05, 0.98, 0.92, 0.84, 0.81, 0.78]
birth_rate = np.tile(birth_rate, 16)
tot_items["출산율"] = birth_rate

In [11]:
tot_items.head(33)

,시도별,농축수산물,공업제품,전기 · 가스 · 수도,집세,공공서비스,개인서비스,출산율
시점,,,,,,,,
2012,서울특별시,84.572,94.385,116.948,85.828,96.900,85.290,1.30
2013,서울특별시,83.128,95.505,122.581,88.279,97.600,86.444,1.19
2014,서울특별시,80.868,97.119,127.783,90.754,98.230,87.971,1.21
2015,서울특별시,83.425,97.842,116.394,93.574,99.893,89.690,1.24
2016,서울특별시,86.541,97.718,103.955,95.904,101.421,92.102,1.17
2017,서울특별시,92.974,98.660,102.933,97.917,102.209,94.468,1.05
2018,서울특별시,95.673,99.578,99.726,98.935,102.459,96.953,0.98
2019,서울특별시,92.937,99.897,101.541,99.258,102.442,98.815,0.92
2020,서울특별시,100.000,100.000,100.000,100.000,100.000,100.000,0.84
2021,서울특별시,107.860,101.510,97.660,101.610,100.800,102.510,0.81
2022,서울특별시,111.670,107.430,112.300,103.350,101.510,108.110,0.78
2012,부산광역시,86.980,94.925,111.049,93.777,98.489,84.264,1.30
2013,부산광역시,87.529,95.998,116.215,95.999,99.153,85.776,1.19
2014,부산광역시,84.518,97.364,120.596,97.126,100.562,87.418,1.21
2015,부산광역시,86.150,98.010,111.890,98.120,100.991,89.327,1.24
2016,부산광역시,89.391,97.573,103.359,99.193,101.722,92.390,1.17
2017,부산광역시,93.013,98.882,102.059,100.272,102.858,94.583,1.05
2018,부산광역시,97.364,100.039,99.908,100.607,103.517,97.195,0.98
2019,부산광역시,95.724,100.137,101.377,100.129,102.649,99.194,0.92
2020,부산광역시,100.000,100.000,100.000,100.000,100.000,100.000,0.84
2021,부산광역시,108.790,102.030,97.820,100.870,100.750,102.780,0.81
2022,부산광역시,112.590,108.630,108.910,102.270,101.680,108.040,0.78
2012,대구광역시,84.368,95.859,112.992,90.066,97.648,83.199,1.30
2013,대구광역시,83.572,96.569,117.964,93.426,98.335,85.512,1.19
2014,대구광역시,83.276,97.901,122.355,95.756,98.714,87.058,1.21
2015,대구광역시,84.536,97.875,114.992,97.941,99.582,88.791,1.24
2016,대구광역시,88.419,97.387,105.144,99.159,100.496,91.502,1.17
2017,대구광역시,92.585,99.039,103.172,99.593,102.689,93.788,1.05
2018,대구광역시,97.164,100.520,100.025,99.784,103.163,96.235,0.98
2019,대구광역시,95.978,100.261,101.365,99.670,102.595,98.802,0.92
2020,대구광역시,100.000,100.000,100.000,100.000,100.000,100.000,0.84
2021,대구광역시,108.960,102.480,97.660,101.330,100.870,102.670,0.81
2022,대구광역시,113.000,109.630,110.080,102.440,101.510,108.490,0.78

In [12]:
tot_items

,시도별,농축수산물,공업제품,전기 · 가스 · 수도,집세,공공서비스,개인서비스,출산율
시점,,,,,,,,
2012,서울특별시,84.572,94.385,116.948,85.828,96.900,85.290,1.30
2013,서울특별시,83.128,95.505,122.581,88.279,97.600,86.444,1.19
2014,서울특별시,80.868,97.119,127.783,90.754,98.230,87.971,1.21
2015,서울특별시,83.425,97.842,116.394,93.574,99.893,89.690,1.24
2016,서울특별시,86.541,97.718,103.955,95.904,101.421,92.102,1.17
...,...,...,...,...,...,...,...,...
2018,제주특별자치도,94.969,101.055,99.231,100.625,100.639,97.601,0.98
2019,제주특별자치도,94.868,100.738,99.392,100.387,100.001,99.235,0.92
2020,제주특별자치도,100.000,100.000,100.000,100.000,100.000,100.000,0.84
2021,제주특별자치도,108.940,103.160,99.360,100.010,100.710,101.950,0.81
2022,제주특별자치도,114.180,111.430,109.410,101.010,101.810,108.670,0.78

In [13]:
# 엑셀 or csv 파일로 저장

In [14]:
tot_items.to_csv("C:/juna27/Git/data/data1/물가지수(품목별).csv",index = True, encoding="EUC-KR")

In [15]:
tot_items_eatout = pd.read_excel("C:\\juna27\\Git\\data\\data1\\품목별_소비자물가지수_품목성질별_2020100__20230425174759(품목별_외식구분_시도별).xlsx")

C:\Users\acorn\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [16]:
tot_items_eatout

,시도별,시점,농축수산물,공업제품,전기 · 가스 · 수도,집세,공공서비스,외식,외식제외
0,서울특별시,2012,84.572,94.385,116.948,85.828,96.900,84.725,85.643
1,서울특별시,2013,83.128,95.505,122.581,88.279,97.600,85.781,86.860
2,서울특별시,2014,80.868,97.119,127.783,90.754,98.230,86.827,88.683
3,서울특별시,2015,83.425,97.842,116.394,93.574,99.893,89.258,89.958
4,서울특별시,2016,86.541,97.718,103.955,95.904,101.421,91.724,92.336
...,...,...,...,...,...,...,...,...,...
171,제주특별자치도,2018,94.969,101.055,99.231,100.625,100.639,97.823,97.424
172,제주특별자치도,2019,94.868,100.738,99.392,100.387,100.001,98.896,99.505
173,제주특별자치도,2020,100.000,100.000,100.000,100.000,100.000,100.000,100.000
174,제주특별자치도,2021,108.940,103.160,99.360,100.010,100.710,103.040,101.080
175,제주특별자치도,2022,114.180,111.430,109.410,101.010,101.810,111.030,106.800

In [17]:
# birth_rate = [1.30, 1.19, 1.21, 1.24, 1.17, 1.05, 0.98, 0.92, 0.84, 0.81, 0.78]

In [18]:
# tot_items_eatout["출산율"] = birth_rate

In [19]:
tot_items_eatout

,시도별,시점,농축수산물,공업제품,전기 · 가스 · 수도,집세,공공서비스,외식,외식제외
0,서울특별시,2012,84.572,94.385,116.948,85.828,96.900,84.725,85.643
1,서울특별시,2013,83.128,95.505,122.581,88.279,97.600,85.781,86.860
2,서울특별시,2014,80.868,97.119,127.783,90.754,98.230,86.827,88.683
3,서울특별시,2015,83.425,97.842,116.394,93.574,99.893,89.258,89.958
4,서울특별시,2016,86.541,97.718,103.955,95.904,101.421,91.724,92.336
...,...,...,...,...,...,...,...,...,...
171,제주특별자치도,2018,94.969,101.055,99.231,100.625,100.639,97.823,97.424
172,제주특별자치도,2019,94.868,100.738,99.392,100.387,100.001,98.896,99.505
173,제주특별자치도,2020,100.000,100.000,100.000,100.000,100.000,100.000,100.000
174,제주특별자치도,2021,108.940,103.160,99.360,100.010,100.710,103.040,101.080
175,제주특별자치도,2022,114.180,111.430,109.410,101.010,101.810,111.030,106.800

In [20]:
tot_items_eatout.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176 entries, 0 to 175
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   시도별           176 non-null    object
 1   시점            176 non-null    int64
 2   농축수산물         176 non-null    float64
 3   공업제품          176 non-null    float64
 4   전기 · 가스 · 수도  176 non-null    float64
 5   집세            176 non-null    float64
 6   공공서비스         176 non-null    float64
 7   외식            176 non-null    float64
 8   외식제외          176 non-null    float64
dtypes: float64(7), int64(1), object(1)
memory usage: 12.5+ KB

In [21]:
tot_items_eatout.set_index("시점", inplace=True)

In [22]:
tot_items_eatout

,시도별,농축수산물,공업제품,전기 · 가스 · 수도,집세,공공서비스,외식,외식제외
시점,,,,,,,,
2012,서울특별시,84.572,94.385,116.948,85.828,96.900,84.725,85.643
2013,서울특별시,83.128,95.505,122.581,88.279,97.600,85.781,86.860
2014,서울특별시,80.868,97.119,127.783,90.754,98.230,86.827,88.683
2015,서울특별시,83.425,97.842,116.394,93.574,99.893,89.258,89.958
2016,서울특별시,86.541,97.718,103.955,95.904,101.421,91.724,92.336
...,...,...,...,...,...,...,...,...
2018,제주특별자치도,94.969,101.055,99.231,100.625,100.639,97.823,97.424
2019,제주특별자치도,94.868,100.738,99.392,100.387,100.001,98.896,99.505
2020,제주특별자치도,100.000,100.000,100.000,100.000,100.000,100.000,100.000
2021,제주특별자치도,108.940,103.160,99.360,100.010,100.710,103.040,101.080
2022,제주특별자치도,114.180,111.430,109.410,101.010,101.810,111.030,106.800

In [23]:
birth_rate = [1.30, 1.19, 1.21, 1.24, 1.17, 1.05, 0.98, 0.92, 0.84, 0.81, 0.78]
birth_rate = np.tile(birth_rate, 16)
tot_items_eatout["출산율"] = birth_rate

In [24]:
tot_items_eatout.head(33)

,시도별,농축수산물,공업제품,전기 · 가스 · 수도,집세,공공서비스,외식,외식제외,출산율
시점,,,,,,,,,
2012,서울특별시,84.572,94.385,116.948,85.828,96.900,84.725,85.643,1.30
2013,서울특별시,83.128,95.505,122.581,88.279,97.600,85.781,86.860,1.19
2014,서울특별시,80.868,97.119,127.783,90.754,98.230,86.827,88.683,1.21
2015,서울특별시,83.425,97.842,116.394,93.574,99.893,89.258,89.958,1.24
2016,서울특별시,86.541,97.718,103.955,95.904,101.421,91.724,92.336,1.17
2017,서울특별시,92.974,98.660,102.933,97.917,102.209,93.998,94.759,1.05
2018,서울특별시,95.673,99.578,99.726,98.935,102.459,97.070,96.876,0.98
2019,서울특별시,92.937,99.897,101.541,99.258,102.442,99.216,98.566,0.92
2020,서울특별시,100.000,100.000,100.000,100.000,100.000,100.000,100.000,0.84
2021,서울특별시,107.860,101.510,97.660,101.610,100.800,102.820,102.300,0.81
2022,서울특별시,111.670,107.430,112.300,103.350,101.510,110.560,106.450,0.78
2012,부산광역시,86.980,94.925,111.049,93.777,98.489,85.107,83.655,1.30
2013,부산광역시,87.529,95.998,116.215,95.999,99.153,86.076,85.562,1.19
2014,부산광역시,84.518,97.364,120.596,97.126,100.562,87.508,87.363,1.21
2015,부산광역시,86.150,98.010,111.890,98.120,100.991,89.337,89.324,1.24
2016,부산광역시,89.391,97.573,103.359,99.193,101.722,92.578,92.263,1.17
2017,부산광역시,93.013,98.882,102.059,100.272,102.858,94.478,94.660,1.05
2018,부산광역시,97.364,100.039,99.908,100.607,103.517,97.731,96.804,0.98
2019,부산광역시,95.724,100.137,101.377,100.129,102.649,99.570,98.919,0.92
2020,부산광역시,100.000,100.000,100.000,100.000,100.000,100.000,100.000,0.84
2021,부산광역시,108.790,102.030,97.820,100.870,100.750,103.120,102.500,0.81
2022,부산광역시,112.590,108.630,108.910,102.270,101.680,111.060,105.600,0.78
2012,대구광역시,84.368,95.859,112.992,90.066,97.648,82.435,83.756,1.30
2013,대구광역시,83.572,96.569,117.964,93.426,98.335,84.624,86.163,1.19
2014,대구광역시,83.276,97.901,122.355,95.756,98.714,86.022,87.811,1.21
2015,대구광역시,84.536,97.875,114.992,97.941,99.582,87.880,89.460,1.24
2016,대구광역시,88.419,97.387,105.144,99.159,100.496,90.677,92.100,1.17
2017,대구광역시,92.585,99.039,103.172,99.593,102.689,92.939,94.407,1.05
2018,대구광역시,97.164,100.520,100.025,99.784,103.163,95.903,96.478,0.98
2019,대구광역시,95.978,100.261,101.365,99.670,102.595,99.131,98.565,0.92
2020,대구광역시,100.000,100.000,100.000,100.000,100.000,100.000,100.000,0.84
2021,대구광역시,108.960,102.480,97.660,101.330,100.870,102.620,102.710,0.81
2022,대구광역시,113.000,109.630,110.080,102.440,101.510,110.570,106.920,0.78

In [25]:
tot_items_eatout

,시도별,농축수산물,공업제품,전기 · 가스 · 수도,집세,공공서비스,외식,외식제외,출산율
시점,,,,,,,,,
2012,서울특별시,84.572,94.385,116.948,85.828,96.900,84.725,85.643,1.30
2013,서울특별시,83.128,95.505,122.581,88.279,97.600,85.781,86.860,1.19
2014,서울특별시,80.868,97.119,127.783,90.754,98.230,86.827,88.683,1.21
2015,서울특별시,83.425,97.842,116.394,93.574,99.893,89.258,89.958,1.24
2016,서울특별시,86.541,97.718,103.955,95.904,101.421,91.724,92.336,1.17
...,...,...,...,...,...,...,...,...,...
2018,제주특별자치도,94.969,101.055,99.231,100.625,100.639,97.823,97.424,0.98
2019,제주특별자치도,94.868,100.738,99.392,100.387,100.001,98.896,99.505,0.92
2020,제주특별자치도,100.000,100.000,100.000,100.000,100.000,100.000,100.000,0.84
2021,제주특별자치도,108.940,103.160,99.360,100.010,100.710,103.040,101.080,0.81
2022,제주특별자치도,114.180,111.430,109.410,101.010,101.810,111.030,106.800,0.78

In [26]:
# 엑셀 or csv 파일로 저장

In [27]:
tot_items_eatout.to_csv("C:/juna27/Git/data/data1/물가지수(품목별_외식).csv",index = True, encoding="EUC-KR")

# ----------------------------------------

In [28]:
item_ext = pd.read_excel("C:\\juna27\\Git\\data\\data1\\품목별_소비자물가지수_품목성질별_2020100__20230425190026(물가지수_단어추출_행렬전환).xlsx")

In [29]:
item_ext.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176 entries, 0 to 175
Data columns (total 48 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   시도별         176 non-null    object
 1   시점          176 non-null    int64
 2   분유          176 non-null    float64
 3   이유식         176 non-null    float64
 4   TV          176 non-null    float64
 5   영상음향기기      176 non-null    float64
 6   휴대용멀티미디어기기  176 non-null    float64
 7   악기          176 non-null    float64
 8   유아동복        176 non-null    float64
 9   유아용학습교재     176 non-null    float64
 10  초등학교학습서     176 non-null    float64
 11  중학교학습서      176 non-null    float64
 12  고등학교학습서     176 non-null    float64
 13  아동화         176 non-null    float64
 14  장난감         176 non-null    float64
 15  반려동물용품      176 non-null    float64
 16  종이문구        176 non-null    float64
 17  기타문구        176 non-null    float64
 18  필기구         176 non-null    float64
 19  회화용구        176 non-null    float64
 20  유모차         176 non-null    float64
 21  유치원납입금      176 non-null    float64
 22  보육시설이용료     176 non-null    float64
 23  요양시설이용료     176 non-null    float64
 24  반려동물관리비     176 non-null    float64
 25  노래방이용료      176 non-null    float64
 26  놀이시설이용료     176 non-null    float64
 27  운동경기관람료     176 non-null    float64
 28  영화관람료       176 non-null    float64
 29  공연예술관람료     176 non-null    float64
 30  관람시설이용료     176 non-null    float64
 31  문화강습료       176 non-null    float64
 32  온라인콘텐츠이용료   176 non-null    float64
 33  초등학생학원비     176 non-null    float64
 34  중학생학원비      176 non-null    float64
 35  고등학생학원비     176 non-null    float64
 36  음악학원비       176 non-null    float64
 37  미술학원비       176 non-null    float64
 38  운동학원비       176 non-null    float64
 39  전산학원비       176 non-null    float64
 40  가정학습지       176 non-null    float64
 41  이러닝이용료      176 non-null    float64
 42  학교보충교육비     176 non-null    float64
 43  외국어학원비      176 non-null    float64
 44  운동강습료       176 non-null    float64
 45  미용료         176 non-null    float64
 46  뷰티미용료       176 non-null    float64
 47  산후조리원이용료    176 non-null    float64
dtypes: float64(46), int64(1), object(1)
memory usage: 66.1+ KB

In [30]:
# item_ext_t = item_ext.T

In [31]:
# item_ext_t_drop = item_ext_t.dropna()

In [32]:
# item_ext = item_ext_t_drop.T

In [33]:
item_ext

,시도별,시점,분유,이유식,TV,영상음향기기,휴대용멀티미디어기기,악기,유아동복,유아용학습교재,...,운동학원비,전산학원비,가정학습지,이러닝이용료,학교보충교육비,외국어학원비,운동강습료,미용료,뷰티미용료,산후조리원이용료
0,서울특별시,2012,98.660,95.056,202.849,98.947,94.083,90.331,89.824,89.448,...,74.969,96.705,94.766,106.470,105.353,84.735,80.280,83.856,89.814,98.461
1,서울특별시,2013,98.974,95.798,191.743,106.726,92.560,93.632,94.456,91.265,...,77.073,99.237,96.371,108.184,104.534,86.870,82.648,86.386,91.025,96.020
2,서울특별시,2014,106.709,96.081,175.617,105.715,92.888,92.388,96.644,91.465,...,80.869,99.668,96.231,108.184,103.450,90.619,89.525,93.446,91.103,92.851
3,서울특별시,2015,111.558,98.969,157.692,105.991,88.127,91.936,97.822,95.359,...,84.884,99.732,95.129,109.348,100.281,91.298,91.577,94.548,91.800,93.477
4,서울특별시,2016,102.943,97.386,143.824,106.690,91.959,91.157,99.750,95.855,...,88.428,99.310,96.660,111.252,95.280,92.590,93.462,95.255,93.035,94.208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,제주특별자치도,2018,92.552,91.736,117.371,102.351,101.444,99.655,103.455,98.334,...,93.133,91.365,97.091,111.252,119.496,85.049,96.591,97.178,98.949,96.865
172,제주특별자치도,2019,93.515,97.821,108.932,100.064,102.703,99.800,101.983,98.358,...,95.994,95.869,100.000,120.623,113.724,92.011,100.000,98.868,99.825,99.417
173,제주특별자치도,2020,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,...,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000
174,제주특별자치도,2021,103.910,100.000,97.820,98.130,99.070,100.340,98.990,100.310,...,100.680,100.270,99.730,107.460,83.210,100.000,103.200,103.300,101.850,100.580
175,제주특별자치도,2022,103.630,100.150,96.030,99.450,100.510,102.640,102.730,100.320,...,103.620,100.270,103.730,110.010,82.950,100.000,105.570,108.800,108.400,101.490

In [34]:
# birth_rate = [1.30, 1.19, 1.21, 1.24, 1.17, 1.05, 0.98, 0.92, 0.84, 0.81, 0.78]

In [35]:
# item_ext["출산율"] = birth_rate

In [36]:
item_ext

,시도별,시점,분유,이유식,TV,영상음향기기,휴대용멀티미디어기기,악기,유아동복,유아용학습교재,...,운동학원비,전산학원비,가정학습지,이러닝이용료,학교보충교육비,외국어학원비,운동강습료,미용료,뷰티미용료,산후조리원이용료
0,서울특별시,2012,98.660,95.056,202.849,98.947,94.083,90.331,89.824,89.448,...,74.969,96.705,94.766,106.470,105.353,84.735,80.280,83.856,89.814,98.461
1,서울특별시,2013,98.974,95.798,191.743,106.726,92.560,93.632,94.456,91.265,...,77.073,99.237,96.371,108.184,104.534,86.870,82.648,86.386,91.025,96.020
2,서울특별시,2014,106.709,96.081,175.617,105.715,92.888,92.388,96.644,91.465,...,80.869,99.668,96.231,108.184,103.450,90.619,89.525,93.446,91.103,92.851
3,서울특별시,2015,111.558,98.969,157.692,105.991,88.127,91.936,97.822,95.359,...,84.884,99.732,95.129,109.348,100.281,91.298,91.577,94.548,91.800,93.477
4,서울특별시,2016,102.943,97.386,143.824,106.690,91.959,91.157,99.750,95.855,...,88.428,99.310,96.660,111.252,95.280,92.590,93.462,95.255,93.035,94.208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,제주특별자치도,2018,92.552,91.736,117.371,102.351,101.444,99.655,103.455,98.334,...,93.133,91.365,97.091,111.252,119.496,85.049,96.591,97.178,98.949,96.865
172,제주특별자치도,2019,93.515,97.821,108.932,100.064,102.703,99.800,101.983,98.358,...,95.994,95.869,100.000,120.623,113.724,92.011,100.000,98.868,99.825,99.417
173,제주특별자치도,2020,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,...,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000
174,제주특별자치도,2021,103.910,100.000,97.820,98.130,99.070,100.340,98.990,100.310,...,100.680,100.270,99.730,107.460,83.210,100.000,103.200,103.300,101.850,100.580
175,제주특별자치도,2022,103.630,100.150,96.030,99.450,100.510,102.640,102.730,100.320,...,103.620,100.270,103.730,110.010,82.950,100.000,105.570,108.800,108.400,101.490

In [37]:
item_ext.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176 entries, 0 to 175
Data columns (total 48 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   시도별         176 non-null    object
 1   시점          176 non-null    int64
 2   분유          176 non-null    float64
 3   이유식         176 non-null    float64
 4   TV          176 non-null    float64
 5   영상음향기기      176 non-null    float64
 6   휴대용멀티미디어기기  176 non-null    float64
 7   악기          176 non-null    float64
 8   유아동복        176 non-null    float64
 9   유아용학습교재     176 non-null    float64
 10  초등학교학습서     176 non-null    float64
 11  중학교학습서      176 non-null    float64
 12  고등학교학습서     176 non-null    float64
 13  아동화         176 non-null    float64
 14  장난감         176 non-null    float64
 15  반려동물용품      176 non-null    float64
 16  종이문구        176 non-null    float64
 17  기타문구        176 non-null    float64
 18  필기구         176 non-null    float64
 19  회화용구        176 non-null    float64
 20  유모차         176 non-null    float64
 21  유치원납입금      176 non-null    float64
 22  보육시설이용료     176 non-null    float64
 23  요양시설이용료     176 non-null    float64
 24  반려동물관리비     176 non-null    float64
 25  노래방이용료      176 non-null    float64
 26  놀이시설이용료     176 non-null    float64
 27  운동경기관람료     176 non-null    float64
 28  영화관람료       176 non-null    float64
 29  공연예술관람료     176 non-null    float64
 30  관람시설이용료     176 non-null    float64
 31  문화강습료       176 non-null    float64
 32  온라인콘텐츠이용료   176 non-null    float64
 33  초등학생학원비     176 non-null    float64
 34  중학생학원비      176 non-null    float64
 35  고등학생학원비     176 non-null    float64
 36  음악학원비       176 non-null    float64
 37  미술학원비       176 non-null    float64
 38  운동학원비       176 non-null    float64
 39  전산학원비       176 non-null    float64
 40  가정학습지       176 non-null    float64
 41  이러닝이용료      176 non-null    float64
 42  학교보충교육비     176 non-null    float64
 43  외국어학원비      176 non-null    float64
 44  운동강습료       176 non-null    float64
 45  미용료         176 non-null    float64
 46  뷰티미용료       176 non-null    float64
 47  산후조리원이용료    176 non-null    float64
dtypes: float64(46), int64(1), object(1)
memory usage: 66.1+ KB

In [38]:
item_ext.set_index("시점", inplace=True)

In [39]:
item_ext

,시도별,분유,이유식,TV,영상음향기기,휴대용멀티미디어기기,악기,유아동복,유아용학습교재,초등학교학습서,...,운동학원비,전산학원비,가정학습지,이러닝이용료,학교보충교육비,외국어학원비,운동강습료,미용료,뷰티미용료,산후조리원이용료
시점,,,,,,,,,,,,,,,,,,,,,
2012,서울특별시,98.660,95.056,202.849,98.947,94.083,90.331,89.824,89.448,76.668,...,74.969,96.705,94.766,106.470,105.353,84.735,80.280,83.856,89.814,98.461
2013,서울특별시,98.974,95.798,191.743,106.726,92.560,93.632,94.456,91.265,77.671,...,77.073,99.237,96.371,108.184,104.534,86.870,82.648,86.386,91.025,96.020
2014,서울특별시,106.709,96.081,175.617,105.715,92.888,92.388,96.644,91.465,79.980,...,80.869,99.668,96.231,108.184,103.450,90.619,89.525,93.446,91.103,92.851
2015,서울특별시,111.558,98.969,157.692,105.991,88.127,91.936,97.822,95.359,86.986,...,84.884,99.732,95.129,109.348,100.281,91.298,91.577,94.548,91.800,93.477
2016,서울특별시,102.943,97.386,143.824,106.690,91.959,91.157,99.750,95.855,88.343,...,88.428,99.310,96.660,111.252,95.280,92.590,93.462,95.255,93.035,94.208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018,제주특별자치도,92.552,91.736,117.371,102.351,101.444,99.655,103.455,98.334,95.856,...,93.133,91.365,97.091,111.252,119.496,85.049,96.591,97.178,98.949,96.865
2019,제주특별자치도,93.515,97.821,108.932,100.064,102.703,99.800,101.983,98.358,98.506,...,95.994,95.869,100.000,120.623,113.724,92.011,100.000,98.868,99.825,99.417
2020,제주특별자치도,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,...,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000
2021,제주특별자치도,103.910,100.000,97.820,98.130,99.070,100.340,98.990,100.310,100.610,...,100.680,100.270,99.730,107.460,83.210,100.000,103.200,103.300,101.850,100.580
2022,제주특별자치도,103.630,100.150,96.030,99.450,100.510,102.640,102.730,100.320,105.160,...,103.620,100.270,103.730,110.010,82.950,100.000,105.570,108.800,108.400,101.490

In [40]:
birth_rate = [1.30, 1.19, 1.21, 1.24, 1.17, 1.05, 0.98, 0.92, 0.84, 0.81, 0.78]
birth_rate = np.tile(birth_rate, 16)
item_ext["출산율"] = birth_rate

In [41]:
item_ext.head(33)

,시도별,분유,이유식,TV,영상음향기기,휴대용멀티미디어기기,악기,유아동복,유아용학습교재,초등학교학습서,...,전산학원비,가정학습지,이러닝이용료,학교보충교육비,외국어학원비,운동강습료,미용료,뷰티미용료,산후조리원이용료,출산율
시점,,,,,,,,,,,,,,,,,,,,,
2012,서울특별시,98.660,95.056,202.849,98.947,94.083,90.331,89.824,89.448,76.668,...,96.705,94.766,106.470,105.353,84.735,80.280,83.856,89.814,98.461,1.30
2013,서울특별시,98.974,95.798,191.743,106.726,92.560,93.632,94.456,91.265,77.671,...,99.237,96.371,108.184,104.534,86.870,82.648,86.386,91.025,96.020,1.19
2014,서울특별시,106.709,96.081,175.617,105.715,92.888,92.388,96.644,91.465,79.980,...,99.668,96.231,108.184,103.450,90.619,89.525,93.446,91.103,92.851,1.21
2015,서울특별시,111.558,98.969,157.692,105.991,88.127,91.936,97.822,95.359,86.986,...,99.732,95.129,109.348,100.281,91.298,91.577,94.548,91.800,93.477,1.24
2016,서울특별시,102.943,97.386,143.824,106.690,91.959,91.157,99.750,95.855,88.343,...,99.310,96.660,111.252,95.280,92.590,93.462,95.255,93.035,94.208,1.17
2017,서울특별시,101.063,98.899,131.350,103.983,97.070,94.130,103.129,98.334,91.743,...,95.935,96.709,111.252,95.390,93.876,94.399,93.950,95.376,94.582,1.05
2018,서울특별시,97.666,91.736,117.371,100.991,101.444,97.044,103.513,98.334,95.856,...,96.000,97.091,111.252,98.610,96.299,95.533,96.715,98.342,97.775,0.98
2019,서울특별시,97.033,97.821,108.932,100.197,102.703,99.380,102.043,98.358,98.506,...,97.062,100.000,120.623,99.692,98.428,99.233,98.593,99.214,99.502,0.92
2020,서울특별시,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,...,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,0.84
2021,서울특별시,100.410,100.000,97.820,96.930,99.070,101.820,98.990,100.310,100.610,...,100.710,99.730,107.460,100.930,103.080,99.410,99.720,100.990,100.860,0.81
2022,서울특별시,101.970,100.150,96.030,99.250,100.510,104.630,102.730,100.320,105.160,...,102.680,103.730,110.010,104.560,108.070,101.910,105.270,104.510,105.240,0.78
2012,부산광역시,95.729,95.640,213.119,98.780,102.180,97.066,89.762,89.448,76.668,...,84.323,94.766,106.470,96.316,80.325,93.284,84.467,79.843,94.357,1.30
2013,부산광역시,96.046,96.194,206.896,109.534,97.274,96.868,94.370,91.265,77.671,...,87.795,96.371,108.184,94.997,82.789,95.532,91.081,83.615,96.216,1.19
2014,부산광역시,101.567,96.559,183.490,108.373,95.185,95.096,96.559,91.465,79.980,...,87.795,96.231,108.184,97.591,85.519,95.316,91.795,89.620,94.334,1.21
2015,부산광역시,104.549,98.969,157.692,108.959,88.127,94.441,97.731,95.359,86.986,...,90.017,95.129,109.348,94.936,86.697,95.686,93.803,91.764,95.298,1.24
2016,부산광역시,99.943,97.386,143.824,107.914,91.959,94.295,99.661,95.855,88.343,...,92.124,96.660,111.252,93.435,88.685,96.048,93.562,91.863,93.351,1.17
2017,부산광역시,95.921,98.899,131.350,103.082,97.070,97.428,103.057,98.334,91.743,...,92.124,96.709,111.252,93.435,91.060,96.048,96.323,91.348,91.740,1.05
2018,부산광역시,91.452,91.736,117.371,100.024,101.444,100.263,103.453,98.334,95.856,...,94.265,97.091,111.252,93.665,92.632,97.558,96.933,99.099,89.117,0.98
2019,부산광역시,93.562,97.821,108.932,99.666,102.703,101.306,101.979,98.358,98.506,...,97.429,100.000,120.623,97.763,96.472,99.737,99.300,99.978,96.063,0.92
2020,부산광역시,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,...,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,0.84
2021,부산광역시,98.220,100.000,97.820,98.050,99.070,100.630,98.990,100.310,100.610,...,100.000,99.730,107.460,105.960,99.930,100.000,100.220,103.310,104.170,0.81
2022,부산광역시,98.350,100.150,96.030,99.970,100.510,104.120,102.730,100.320,105.160,...,103.420,103.730,110.010,111.120,103.050,100.670,103.700,107.340,112.840,0.78
2012,대구광역시,102.215,93.241,201.658,101.949,99.636,98.398,89.749,89.448,76.668,...,77.332,94.766,106.470,91.699,78.845,90.444,70.510,95.567,90.285,1.30
2013,대구광역시,98.096,95.247,196.027,109.979,95.713,100.121,94.373,91.265,77.671,...,82.018,96.371,108.184,89.094,82.753,91.442,76.310,94.975,92.321,1.19
2014,대구광역시,108.440,94.794,176.261,106.254,93.645,97.224,96.559,91.465,79.980,...,87.353,96.231,108.184,86.806,84.087,92.904,82.965,94.159,89.592,1.21
2015,대구광역시,113.013,98.969,157.692,106.511,88.127,94.747,97.734,95.359,86.986,...,90.534,95.129,109.348,87.957,86.445,93.371,89.302,91.640,88.464,1.24
2016,대구광역시,105.099,97.386,143.824,106.498,91.959,91.026,99.661,95.855,88.343,...,93.837,96.660,111.252,92.780,90.435,93.869,90.842,92.096,91.044,1.17
2017,대구광역시,103.064,98.899,131.350,103.405,97.070,94.027,103.040,98.334,91.743,...,95.797,96.709,111.252,97.933,94.910,97.003,91.849,93.860,93.366,1.05
2018,대구광역시,98.897,91.736,117.371,100.161,101.444,97.843,103.444,98.334,95.856,...,96.917,97.091,111.252,97.801,96.949,99.737,96.129,97.029,95.952,0.98
2019,대구광역시,98.910,97.821,108.932,99.483,102.703,99.845,101.969,98.358,98.506,...,96.917,100.000,120.623,98.467,98.160,100.000,99.290,97.888,98.021,0.92
2020,대구광역시,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,...,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,0.84
2021,대구광역시,98.010,100.000,97.820,98.240,99.070,100.000,98.990,100.310,100.610,...,103.040,99.730,107.460,103.040,100.670,100.000,104.190,102.210,101.610,0.81
2022,대구광역시,99.310,100.150,96.030,101.300,100.510,101.160,102.730,100.320,105.160,...,105.790,103.730,110.010,107.000,103.640,100.000,108.680,104.140,102.570,0.78

In [42]:
item_ext

,시도별,분유,이유식,TV,영상음향기기,휴대용멀티미디어기기,악기,유아동복,유아용학습교재,초등학교학습서,...,전산학원비,가정학습지,이러닝이용료,학교보충교육비,외국어학원비,운동강습료,미용료,뷰티미용료,산후조리원이용료,출산율
시점,,,,,,,,,,,,,,,,,,,,,
2012,서울특별시,98.660,95.056,202.849,98.947,94.083,90.331,89.824,89.448,76.668,...,96.705,94.766,106.470,105.353,84.735,80.280,83.856,89.814,98.461,1.30
2013,서울특별시,98.974,95.798,191.743,106.726,92.560,93.632,94.456,91.265,77.671,...,99.237,96.371,108.184,104.534,86.870,82.648,86.386,91.025,96.020,1.19
2014,서울특별시,106.709,96.081,175.617,105.715,92.888,92.388,96.644,91.465,79.980,...,99.668,96.231,108.184,103.450,90.619,89.525,93.446,91.103,92.851,1.21
2015,서울특별시,111.558,98.969,157.692,105.991,88.127,91.936,97.822,95.359,86.986,...,99.732,95.129,109.348,100.281,91.298,91.577,94.548,91.800,93.477,1.24
2016,서울특별시,102.943,97.386,143.824,106.690,91.959,91.157,99.750,95.855,88.343,...,99.310,96.660,111.252,95.280,92.590,93.462,95.255,93.035,94.208,1.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018,제주특별자치도,92.552,91.736,117.371,102.351,101.444,99.655,103.455,98.334,95.856,...,91.365,97.091,111.252,119.496,85.049,96.591,97.178,98.949,96.865,0.98
2019,제주특별자치도,93.515,97.821,108.932,100.064,102.703,99.800,101.983,98.358,98.506,...,95.869,100.000,120.623,113.724,92.011,100.000,98.868,99.825,99.417,0.92
2020,제주특별자치도,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,...,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,0.84
2021,제주특별자치도,103.910,100.000,97.820,98.130,99.070,100.340,98.990,100.310,100.610,...,100.270,99.730,107.460,83.210,100.000,103.200,103.300,101.850,100.580,0.81
2022,제주특별자치도,103.630,100.150,96.030,99.450,100.510,102.640,102.730,100.320,105.160,...,100.270,103.730,110.010,82.950,100.000,105.570,108.800,108.400,101.490,0.78

In [43]:
# 엑셀 or csv 파일로 저장

In [44]:
item_ext.to_csv("C:/juna27/Git/data/data1/물가지수(단어_추출).csv",index = True, encoding="EUC-KR")